services:
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CITIES=${SERVER_CITIES}
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}

      # Proton DNS and disable DoT/Unbound to avoid Cloudflare DNS
      - DOT=${DOT}
      - DNS_ADDRESS=${DNS_ADDRESS}
      - BLOCK_OUTSIDE_DNS=${BLOCK_OUTSIDE_DNS}

    volumes:
      - gluetun-config:/gluetun

    # Expose qB WebUI (inside qb is 8080) via gluetun to host 8081 by default
    ports:
      - "${HOST_WEBUI_PORT:-8081}:8080/tcp"
      # Optional: expose gluetun control server for debug (not required for the mod when sharing network)
      # - "${GLUETUN_CONTROL_PORT:-8000}:8000/tcp"

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://google.com || exit 1"]
      interval: 40s
      timeout: 15s
      retries: 5

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped

    # Ensure qB only goes out through gluetun (no leaks)
    network_mode: "service:gluetun"

    depends_on:
      gluetun:
        condition: service_healthy

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080

      # Port Forwarding Mod (Syncs qBittorrent with Gluetun)
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_GTN_API_KEY=${GSP_GTN_API_KEY}
      - GSP_QBITTORRENT_PORT=${GSP_QBITTORRENT_PORT}
      - GSP_MINIMAL_LOGS=false

    volumes:
      - ${CONFIG_ROOT}:/config
      - ${DOWNLOADS_ROOT}:/Downloads

    ulimits:
      nofile:
        soft: 32768
        hard: 65536

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_LABEL_ENABLE=true

volumes:
  gluetun-config:
